path: ''
profiles:
  local-author:
    args:
      - 'clean'
      - 'install'
      - '-e'
    properties:
      skipTests: true
      version: 1.8
  default:
    args:
      - 'compiler:compile'
      - 'install'
      - '-e'
    properties:
      skipTests: true